version: '3'

services:
  php:
    build: .
    volumes:
      - .:/var/www/app

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/app
      - ./docker/nginx.conf.d/:/etc/nginx/conf.d/

  redis:
    image: redis:latest
