# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
parameters:
    quotes_file_location: '%kernel.project_dir%/data/quotes.json'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/App/*'
        exclude: '../src/App/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    QuotesApi\Core\QueryBus\QueryBus:
        alias: 'Infrastructure\QueryBus\MessengerQueryBus'
        public: true

    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']

    Infrastructure\:
        resource: '../src/Infrastructure/*'

    QuotesApi\:
        resource: '../src/QuotesApi/*'
        exclude: '../src/QuotesApi/**/{Model,Query/Query,Query/Result}'

    command_handlers:
        namespace: 'QuotesApi\'
        resource: '%kernel.project_dir%/src/QuotesApi/**/*CommandHandler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    query_handlers:
        namespace: 'QuotesApi\'
        resource: '%kernel.project_dir%/src/QuotesApi/**/*QueryHandler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    Infrastructure\Quote\FileQuoteProvider:
        arguments:
            $quotesFile: '%quotes_file_location%'

    Infrastructure\Quote\CachingQuoteProvider:
        arguments:
            $innerProvider: '@Infrastructure\Quote\FileQuoteProvider'

    QuotesApi\Model\ShoutingQuoteProvider:
        arguments:
            $innerProvider: '@Infrastructure\Quote\CachingQuoteProvider'

    QuotesApi\Model\QuoteProvider: '@QuotesApi\Model\ShoutingQuoteProvider'

    Predis\Client:
        arguments:
            - '%env(REDIS_DSN)%'

    Infrastructure\Cache\Cache: '@Infrastructure\Cache\PredisCache'
